glamazer/artists/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^change_password/(?P<email_token>.*)', 'glamazer.users.views.change_password', name='change_password'),
    url(r'^forgotten_password/', 'glamazer.users.views.forgotten_password', name='forgotten_password'),
    url(r'^sign_up/$', 'glamazer.artists.views.sign_up', name='artists_sign_up'),
    url(r'^sign_up/facebook$', 'glamazer.artists.views.facebook_registration', name='artists_sign_up_facebook'),
    url(r'^profile/$', 'glamazer.artists.views.profile', name='artists_profile'),
    url(r'^profile/(?P<artist_id>.*)', 'glamazer.artists.views.profile', name='artists_profile_user'),
    url(r'^settings/profile$', 'glamazer.artists.views.edit', name='edit_artist_profile'),
    url(r'^settings/account$', 'glamazer.artists.views.account', name='edit_artist_account'),
    url(r'^settings/schedule$', 'glamazer.artists.views.schedule', name='artist_schedule'),
    url(r'^settings/policy$', 'glamazer.artists.views.cancellation_policy', name='artist_cancellation_policy'),
    url(r'^settings/payments$', 'glamazer.artists.views.payments', name='artist_payments'),
    url(r'^upload/$', 'glamazer.artists.views.upload', name='upload'),
    url(r'^listings/all/$', 'glamazer.artists.views.all_listings', name='all_listing'),
    url(r'^bookings/$', 'glamazer.artists.views.bookings', name='artists_bookings'),
    url(r'^calendar/$', 'glamazer.artists.views.calendar', name='artists_calendar'),
    url(r'^statistic/$', TemplateView.as_view(template_name="artists/stats.html"), name='artists_statistic'),
    url(r'^wallet/$', 'glamazer.artists.views.wallet', name='artists_wallet'),
    url(r'^withdraw/$', 'glamazer.artists.views.withdraw', name='artists_withdraw'),
    url(r'^notifications/$', 'glamazer.notifications.views.show_notifications', name='artist_notifications'),
    url(r'^get_chart_info/$', 'glamazer.artists.views.get_chart_info', name='get_chart_info'),
)

glamazer/listings/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^confirm/', 'glamazer.listings.views.confirm', name='booking_confirm'),
    url(r'^check_availability/$', 'glamazer.listings.views.check_availability', name='check_availability'),
    url(r'^edit/(?P<listing_id>.*)$', 'glamazer.listings.views.edit', name='edit_listing'),
    url(r'^delete/(?P<listing_id>.*)$', 'glamazer.listings.views.delete', name='delete_listing'),
    url(r'^activate/(?P<listing_id>.*)$', 'glamazer.listings.views.activate', name='activate_listing'),
    url(r'^(?P<listing_id>.*)$', 'glamazer.listings.views.show', name='listing'),
)

glamazer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'glamazer.core.views.home', name='home'),
    url(r'^venues/', 'glamazer.core.views.base', name='venues'),
    url(r'^catering/', 'glamazer.core.views.base', name='catering'),
    url(r'^drinks/', 'glamazer.core.views.base', name='drinks'),
    url(r'^music/', 'glamazer.core.views.base', name='music'),
    url(r'^entertainment/', 'glamazer.core.views.base', name='entertainment'),
    url(r'^equipment/', 'glamazer.core.views.base', name='equipment'),
    url(r'^decoration/', 'glamazer.core.views.base', name='decoration'),
    url(r'^party_goods/', 'glamazer.core.views.base', name='party'),
    url(r'^more/', 'glamazer.core.views.base', name='more'),
    url(r'^contest/', 'glamazer.core.views.base', name='contest'),
    url(r'^leaderboards/', 'glamazer.core.views.base', name='leaderboards'),
    url(r'^result/', 'glamazer.core.views.search', name='result'),
    url(r'^get_notifications/', 'glamazer.notifications.views.get_notifications', name='short_notifications'),
    url(r'^get_notifications_count/', 'glamazer.notifications.views.get_notification_count', name='notification_count'),
    url(r'^autocomplete_tags/', 'glamazer.core.views.autocomplete_tags', name='autocomplete_tags'),
    url(r'^sign_up/', TemplateView.as_view(template_name="sign_up.html"), name='signup'),
    url(r'^calendar/', TemplateView.as_view(template_name="core/calendar.html"), name='calender'),
    url(r'^success/', TemplateView.as_view(template_name="payments/success.html"), name='calender'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('glamazer.users.urls')),
    url(r'^artists/', include('glamazer.artists.urls')),
    url(r'^listings/', include('glamazer.listings.urls')),
    url(r'^favorites/', include('glamazer.favorites.urls')),
    url(r'^reviews/', include('glamazer.reviews.urls')),
    url(r'^success/', 'glamazer.payments.views.success_payment', name='success'),
    url(r'^error/', 'glamazer.payments.views.error_payment', name='error'),
    url(r'^cancel/', 'glamazer.payments.views.cancel_payment', name='cancel'),
    url(r'^start_payment/', 'glamazer.payments.views.start_payment', name='payment'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

glamazer/listings/models.py
import os

from pyelasticsearch import ElasticSearch

from haystack.utils.geo import Point
from sorl.thumbnail import get_thumbnail

from django.db import models

from glamazer.settings import MEDIA_ROOT, ELASTIC_SEARCH_URL, NOTIFICATIONS_SHORT, NOTIFICATIONS_LONG, LISTING_STATUS
from glamazer.core.helpers import current_time, get_rate
from glamazer.followers.models import Followers
from glamazer.notifications.models import Notification
from glamazer.artists.models import Artist


class Listing(models.Model):
    
    artist = models.ForeignKey(Artist)
    picture = models.CharField(max_length=128, help_text='The path to the images. Never change it.')
    picture_cover = models.CharField(max_length=128)
    title = models.CharField(max_length=128)
    description = models.TextField()
    price = models.FloatField()
    likes = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    metadata = models.CharField(max_length=16)
    duration = models.IntegerField(default=0, help_text="1800=00:30 | 3600=1:00 | 5400=1:30 | 7200=2:00 | 9000=2:30 | 10800=3:00 | 12600=3:30 | 14400=4:00")
    status = models.IntegerField(default=0, choices=LISTING_STATUS)
    uploaded = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_style(self):
        return self.artist.get_style()

    def get_picture(self):
        return self.picture_cover

    def get_all_pictures(self):
        pictures = []
        cover = self.picture_cover.split("/")[-1]
        full_path = MEDIA_ROOT + self.picture[7:]
        for p in os.listdir(full_path):
            if not p == cover:
                pictures.append(full_path + p)
        return pictures

    def get_location(self):
        return Point(self.artist.lng, self.artist.lat)

    def get_artist_avatar(self):
        return self.artist.get_avatar()

    def get_artist_id(self):
        return self.artist.id

    def get_artist_avatar(self):
        return self.artist.get_avatar()

    def get_tags(self):
        listings = ListingTags.objects.filter(listing=self).select_related("tags")
        return [x.tags.tag for x in listings]

    def get_rating(self):
        from glamazer.reviews.models import Review
        reviews = Review.objects.select_related().filter(listing=self)
        rate = get_rate(reviews)
        return rate

    def view_all_pictures(self):
        all_pictures = self.get_all_pictures()
        all_pictures.append(self.get_picture())
        thumbs = '<ul>'
        for pic in all_pictures:
            print(get_thumbnail(pic, '240x143', crop='center', quality=99))
            thumbs += '<li><img src="'
            thumbs +=  get_thumbnail(pic, '240x143', crop='center', quality=99).url
            thumbs +=  '"/></li>'
        return thumbs

    view_all_pictures.allow_tags = True
    view_all_pictures.short_description = "Pictures"
    

    def save(self, force_insert=False, force_update=False, **kwargs):
        es = ElasticSearch(ELASTIC_SEARCH_URL)
        if self.id:
            location = self.get_location()
            location_es = "{0},{1}".format(location.y, location.x)
            es.update('glamazer', 'modelresult', 'listings.listing.{0}'.format(self.id),
                script="ctx._source.listing_id = listing;" +
                "ctx._source.artist_id = artist;" +
                "ctx._source.artist_avatar = artist_avatar;" +
                "ctx._source.title = title;" +
                "ctx._source.location = location;" +
                "ctx._source.description = description;" +
                "ctx._source.get_picture = get_picture;" +
                "ctx._source.metadata = metadata;" +
                "ctx._source.price = price;" +
                "ctx._source.likes = likes;" +
                "ctx._source.comments = comments;" +
                "ctx._source.tags = tags;" +
                "ctx._source.status = status;" +
                "ctx._source.style = style;" +
                "ctx._source.rating = rating",
                params={
                    'listing':self.id, 
                    'artist':self.get_artist_id(),
                    'artist_avatar':self.get_artist_avatar(),
                    'title':self.title,
                    'location':location_es,
                    'description':self.description, 
                    'get_picture':self.get_picture(),
                    'metadata':self.metadata,
                    'price':self.price,
                    'likes':self.likes,
                    'comments':self.comments,
                    'tags':self.get_tags(),
                    'status':self.status,
                    'style':self.get_style(),
                    'rating':self.get_rating()
                    })
            super(Listing, self).save(force_insert, force_update)
        else:
            super(Listing, self).save(force_insert, force_update)

            artist_user = self.artist.user
            artist_name = artist_user.first_name
            followers = Followers.objects.select_related().filter(artist=self.artist)
            for follower in followers:
                Notification.objects.create(
                    sender = artist_user,
                    receiver = follower.user,
                    time = current_time(),
                    short_text = NOTIFICATIONS_SHORT[10].format(artist=artist_name),
                    long_text = NOTIFICATIONS_LONG[10].format(artist=artist_name, listing=self.title, user_id=self.artist_id, metadata=self.id),
                )

            location = self.get_location()
            location_es = "{0},{1}".format(location.y, location.x)
            es.index('glamazer', 'modelresult', 
                {
                    'listing_id': self.id,
                    'artist_id': self.artist_id,
                    'artist_avatar':self.get_artist_avatar(),
                    'title': self.title,
                    'location': location_es,
                    'description': self.description,
                    'get_picture': self.get_picture(),
                    'metadata': self.metadata,
                    'price': self.price,
                    'likes': self.likes,
                    'comments':self.comments,
                    'tags': self.get_tags(),
                    'status':self.status,
                    'style':self.get_style(),
                    'rating':self.get_rating()
                }, id='listings.listing.{0}'.format(self.id))
            es.refresh('glamazer')


class Tags(models.Model):
    tag = models.TextField()


class ListingTags(models.Model):
    listing = models.ForeignKey(Listing)
    tags = models.ForeignKey(Tags)


class ListingView(models.Model):
    listing = models.ForeignKey(Listing)
    date = models.DateField(auto_now_add=True)
    views = models.IntegerField(default=0)

glamazer/listings/forms.py
import string
import random
import os
import base64
import re

from io import BytesIO
from PIL import Image

from django import forms

from glamazer.core.helpers import get_object_or_None
from glamazer.listings.models import Listing, Tags, ListingTags
from glamazer.settings import MEDIA_URL, MEDIA_ROOT, DURATION


class EditListing(forms.Form):
    
    title = forms.CharField(required=True, widget=forms.TextInput())
    description = forms.CharField(required=True, widget=forms.TextInput())
    price = forms.CharField(required=True, widget=forms.NumberInput())
    tags = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "listing_edit", "value":" ", "data-option":"LONDON"}))
    duration = forms.ChoiceField(widget=forms.Select(), choices=DURATION)
    cover = forms.CharField(required=False, widget=forms.HiddenInput(), initial=0)
    deleted = forms.CharField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = Listing

    def clean_price(self):
        data = self.cleaned_data
        price = data['price']
        if not (len(price) in range(5) and price.isdigit()):
            raise forms.ValidationError('Please enter a valid price.')

        return price

    def save(self, listing, FILES):
        data = self.cleaned_data
        pictures = FILES.getlist('files')
        hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(6))

        my_dir = MEDIA_ROOT + listing.picture[7:]

        deletes_files = data['deleted']
        if deletes_files:
            deletes_files = data['deleted'].split(',')[:-1]
            for d in deletes_files:
                os.remove(d)
        
        os.chdir(my_dir)

        cover = data["cover"]

        artist_id = str(listing.artist_id)

        for index, picture in enumerate(pictures):
            dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
            my_file = dataUrlPattern.match(picture).group(2)

            hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(6))

            if cover.isdigit() and index == int(cover):
                full_path = MEDIA_ROOT + 'artists/' + artist_id + '/listings/' + listing.metadata + '/' + hash_name + '.jpeg'
                cover = full_path
            else:
                full_path = MEDIA_ROOT + 'artists/' + artist_id + '/listings/' + listing.metadata + '/' + hash_name +'.jpeg'

            #if the folder doesn't exist, create on
            d = os.path.dirname(full_path)
            if not os.path.exists(d):
                os.makedirs(d)

            im = Image.open(BytesIO(base64.b64decode(my_file.encode('ascii'))))
            im.save(full_path, 'JPEG')


        ListingTags.objects.filter(listing=listing).delete()

        tags = data['tags'].split(',')
        for tag in tags:
            tag = tag.lower()
            current_tag = get_object_or_None(Tags, tag=tag)
            if not current_tag:
                current_tag = Tags.objects.create(tag=tag)

            ListingTags.objects.create(listing=listing, tags=current_tag)

        if cover:
            listing.picture_cover = cover
        listing.title = data['title']
        listing.description = data['description']
        listing.price = data['price']
        listing.duration = int(data['duration'])
        listing.save()

        return listing

templates/artists/settings.html
{% extends "master.html" %}
{% load i18n %}
{% load thumbnail %}

{% block meta %}
    <title>Partytask – booking platform for top event professionals and service providers - Artist Settings</title>
{% endblock meta %}

{% block stylesheets %}
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/select2.css">
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/imgselectarea.css">
{% endblock stylesheets %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>SETTINGS</span>
    </div>

    {% block msg %}

    {% endblock msg %}
    
    <div class="column">
        <div class="head">
            <ul>
                <li><a href="{% url 'edit_artist_profile' %}"{% if 'profile' in request.path %} class="active"{% endif %}>PROFILE</a></li>
                <li><a href="{% url 'edit_artist_account' %}"{% if 'account' in request.path %} class="active"{% endif %}>ACCOUNT</a></li>
                <li><a href="{% url 'artist_schedule' %}"{% if 'schedule' in request.path %} class="active"{% endif %}>SCHEDULE</a></li>
                <li><a href="{% url 'artist_cancellation_policy' %}"{% if 'policy' in request.path %} class="active"{% endif %}>POLICY</a></li>
                <li><a href="{% url 'artist_payments' %}"{% if 'payments' in request.path %} class="active"{% endif %}>PAYMENTS</a></li>
            </ul>
        </div>
        {% block settings %}
        {% endblock settings %}
    </div>
</div>

    {% endblock content %}

    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

templates/artists/sign_up.html
{% extends "master.html" %}
{% load thumbnail %}
{% load i18n %}

{% block meta %}
    <title>Partytask – booking platform for top event professionals and service providers - Sign Up</title>
{% endblock meta %}

{% block stylesheets %}
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/select2.css">
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/imgselectarea.css">
{% endblock stylesheets %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>SIGN UP</span>
    </div>

    <div class="column">

        <ul class="progressbar forms">
            <li class="active"><span>STEP 1</span></li>
            <li {% if request.GET.step == '2' or request.GET.step == '3' or request.GET.step == '4' %}class="active"{% endif %}><span>STEP 2</span></li>
            <li {% if request.GET.step == '3' or request.GET.step == '4' %}class="active"{% endif %}><span>STEP 3</span></li>
            <li {% if request.GET.step == '4' %}class="active"{% endif %}><span>STEP 4</span></li>
        </ul>
        
        <div class="forms" {% if request.GET.step != '1' %}style="display: none"{% endif %}>
            <form class="login" method="POST">
                {% csrf_token %}

                <ul>
                    <li><label for="" class="main_label">
                        {% if form.name.errors %}
                            {{ form.name.errors }}
                        {% endif %}
                        Name</label></li>
                    <li>
                        {{ form.name }}
                    </li>
                    <li><label for="" class="main_label">
                        {% if form.email.errors %}
                            {{ form.email.errors }}
                        {% endif %}
                        Email</label></li>
                    <li>
                        {{ form.email }}
                    </li>
                    <li><label for="" class="main_label">
                        {% if form.password.errors %}
                            {{ form.password.errors }}
                        {% endif %}
                        Password</label></li>
                    <li>
                        {{ form.password }}
                    </li>
                    <li><label for="" class="main_label">
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password.errors }}
                        {% endif %}
                        Confirm Password</label></li>
                    <li>
                        {{ form.confirm_password }}
                    </li>
                    <li>
                        <input type="submit" value="Register">
                    </li>
                    <li class="or">
                        <div></div>
                        <div class="or"> OR </div>
                    </li>
                    <li class="facebook">
                        <div class="facebook_icon"></div>
                        <input type="button" value="Register using Facebook" onclick="register_me('artist')">
                        <div class="fb-login-button" data-perms="email" data-scope="email" data-max-rows="1" data-show-faces="false"></div>
                        <div id="fb-root"></div>
                    </li>
                </ul>
            </form>
        </div>

        <div class="forms" {% if request.GET.step != '2' %}style="display: none"{% endif %}>
            <form id="step_2" class="login" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <ul>
                    <li><label for="" class="main_label">
                        {% if form.style.errors %}
                            {{ form.style.errors }}
                        {% endif %}
                        1. What is your business?</label></li>
                    <li>
                        {{ form.style }}
                    </li>
                    <li><label for="" class="main_label">
                        {% if form.specific_style.errors %}
                            {{ form.specific_style.errors }}
                        {% endif %}
                        2. Can you please specify?</label></li>
                    <li>
                        {{ form.specific_style }}
                    </li>
                    <li><label for="" class="main_label">
                        {% if form.avatar.errors %}
                            {{ form.avatar.errors }}
                        {% endif %}
                        {{form.cropped_image}}
                        3. Upload profile picture</label></li>
                    <li>
                        {% thumbnail request.user.artist.get_avatar "150x150" crop="center" as im %}
                            <img id="preview" src="{{ im.url }}">
                        {% endthumbnail %}
                        <div class="upload_button">Click here to upload picture</div>
                        {{ form.avatar}}
                    </li>
                    <li><label for="" class="main_label">
                        {% if form.description.errors %}
                            {{ form.description.errors }}
                        {% endif %}
                        4. Introduce yourself</label></li>
                    <li>
                        {{ form.description }}
                    </li>
                    <li>
                        <input type="submit" value="Save and continue">
                    </li>
                </ul>
            </form>
        </div>

        <div class="forms" {% if request.GET.step != '3' %}style="display: none"{% endif %}>
            <form class="login" method="POST">
                {% csrf_token %}

                <ul>
                    <li><label for="" class="main_label">
                        {% if form.address.errors %}
                            {{ form.address.errors }}
                        {% endif %}
                        1. Submit your location</label></li>
                    <li><label for="" class="main_label">
                        {{ form.address }}
                        {{ form.lat }}
                        {{ form.lng }}
                    </label></li>
                    <li id="maps">
                    </li>

                    <li>

                    </li>

                    <li><label for="" class="main_label">
                        {% if form.mobile_number.errors %}
                            {{ form.mobile_number.errors }}
                        {% endif %}
                        2. Enter your phone number</label></li>
                    <li>
                        {{ form.mobile_number }}
                    </li>

                    <li>
                        <input type="submit" value="Save and continue">
                    </li>
                </ul>
            </form>
        </div>

        <div class="forms" {% if request.GET.step != '4' %}style="display: none"{% endif %}>
            <form class="login listing_upload" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <ul>
                    <li id="gallery_preview" class="multiple_listing">
                        <ul>
                            
                        </ul>
                    </li>

                    <li class="photos_upload">
                        {% if form.cover.errors %}
                            <div class="wrong_picture">{{ form.cover.errors }}</div>
                        {% endif %}
                        <div class="upload_button">Click here to upload picture</div>
                        <input type="file" name="pictures" id="id_picture" class="custom_button active_input" multiple/>
                        {{ form.cover }}
                    </li>
                    <li><label for="" class="main_label">
                        {% if form.title.errors %}
                            {{ form.title.errors }}
                        {% endif %}
                        1. Title</label></li>
                    <li>
                        {{ form.title }}
                    </li>
                    <li><label for="" class="main_label">
                        {% if form.description.errors %}
                            {{ form.description.errors }}
                        {% endif %}
                        2. Description</label></li>
                    <li>
                        {{ form.description }}
                    </li>
                    <li></li>
                    <li class="price"><label for="" class="main_label">
                        {% if form.price.errors %}
                            {{ form.price.errors }}
                        {% endif %}
                        3. Price</label>
                    </li>
                    <li class="price">
                        {{ form.price }}
                    </li>
                    <li class="style"><label for="" class="main_label">
                        {% if form.duration.errors %}
                            {{ form.duration.errors }}
                        {% endif %}4. Duration</label>
                        {{ form.duration }}</li>

                    <li><label for="" class="main_label">
                        {% if form.tags.errors %}
                            {{ form.tags.errors }}
                        {% endif %}
                        5. Tags</label></li>
                    <li>
                        {{ form.tags }}
                    </li>

                    <li>
                        <input type="submit" value="Save and continue">
                    </li>
                </ul>
            </form>
        </div>

    </div>
</div>

    {% endblock content %}
    {% block scripts %}
        <script src="{{STATIC_URL}}js/error.js"></script>
        <script src="{{STATIC_URL}}js/preview.js"></script>
        <script src="http://connect.facebook.net/en_US/all.js"></script>
        <script src="{{STATIC_URL}}js/facebook.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/upload_listing.js"></script>
        <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/google_maps_controller.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/select2.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/imgSelectArea.js"></script>
    {% endblock scripts %}
</body>
</html>

templates/artists/upload.html
{% extends "master.html" %}
{% load i18n %}

{% block meta %}
    <title>Partytask – booking platform for top event professionals and service providers - Upload Listing</title>
{% endblock meta %}

{% block stylesheets %}
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/select2.css">
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/jquery-ui.css">

{% endblock stylesheets %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>ADD NEW LISTING</span>
    </div>

    <div class="column">

        <div class="forms">
            <form class="login listing_upload" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <ul>
                    <li id="gallery_preview" class="multiple_listing">
                        <ul>
                            
                        </ul>
                    </li>

                    <li class="photos_upload">
                        {% if form.cover.errors %}
                            <div class="wrong_picture">{{ form.cover.errors }}</div>
                        {% endif %}
                        <div class="upload_button">Click here to upload picture</div>
                        <input type="file" name="pictures" id="id_picture" class="custom_button active_input" multiple/>
                        {{ form.cover }}
                    </li>
                    <li><label for="" class="main_label">
                        {% if form.title.errors %}
                            {{ form.title.errors }}
                        {% endif %}
                        Title</label></li>
                    <li>
                        {{ form.title }}
                    </li>
                    <li><label for="" class="main_label">
                        {% if form.description.errors %}
                            {{ form.description.errors }}
                        {% endif %}
                        Description</label></li>
                    <li>
                        {{ form.description }}
                    </li>
                    <li></li>
                    <li class="price"><label for="" class="main_label">
                        {% if form.price.errors %}
                            {{ form.price.errors }}
                        {% endif %}
                        Price</label>
                    </li>
                    <li class="price">
                        {{ form.price }}
                    </li>
                    <li class="style"><label for="" class="main_label">
                        {% if form.duration.errors %}
                            {{ form.duration.errors }}
                        {% endif %}
                        Duration</label>{{ form.duration }}</li>
                    <li><label for="" class="main_label">
                        {% if form.tags.errors %}
                            {{ form.tags.errors }}
                        {% endif %}
                        Tags</label></li>
                    <li>
                        {{ form.tags }}
                    </li>

                    <li>
                        <input type="submit" value="Save and continue">
                    </li>

                </ul>
            </form>
        </div>

    </div>
</div>

    {% endblock content %}
    {% block scripts %}
        <script src="{{STATIC_URL}}js/error.js"></script>
        <script src="{{STATIC_URL}}js/preview.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/select2.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/upload_listing.js"></script>
    {% endblock scripts %}
</body>
</html>