glamazer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'glamazer.core.views.home', name='home'),
    url(r'^venues/', 'glamazer.core.views.base', name='venues'),
    url(r'^catering/', 'glamazer.core.views.base', name='catering'),
    url(r'^drinks/', 'glamazer.core.views.base', name='drinks'),
    url(r'^music/', 'glamazer.core.views.base', name='music'),
    url(r'^entertainment/', 'glamazer.core.views.base', name='entertainment'),
    url(r'^equipment/', 'glamazer.core.views.base', name='equipment'),
    url(r'^decoration/', 'glamazer.core.views.base', name='decoration'),
    url(r'^party_goods/', 'glamazer.core.views.base', name='party'),
    url(r'^more/', 'glamazer.core.views.base', name='more'),
    url(r'^contest/', 'glamazer.core.views.base', name='contest'),
    url(r'^leaderboards/', 'glamazer.core.views.base', name='leaderboards'),
    url(r'^result/', 'glamazer.core.views.search', name='result'),
    url(r'^get_notifications/', 'glamazer.notifications.views.get_notifications', name='short_notifications'),
    url(r'^get_notifications_count/', 'glamazer.notifications.views.get_notification_count', name='notification_count'),
    url(r'^autocomplete_tags/', 'glamazer.core.views.autocomplete_tags', name='autocomplete_tags'),
    url(r'^sign_up/', TemplateView.as_view(template_name="sign_up.html"), name='signup'),
    url(r'^calendar/', TemplateView.as_view(template_name="core/calendar.html"), name='calender'),
    url(r'^success/', TemplateView.as_view(template_name="payments/success.html"), name='calender'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('glamazer.users.urls')),
    url(r'^artists/', include('glamazer.artists.urls')),
    url(r'^listings/', include('glamazer.listings.urls')),
    url(r'^favorites/', include('glamazer.favorites.urls')),
    url(r'^reviews/', include('glamazer.reviews.urls')),
    url(r'^success/', 'glamazer.payments.views.success_payment', name='success'),
    url(r'^error/', 'glamazer.payments.views.error_payment', name='error'),
    url(r'^cancel/', 'glamazer.payments.views.cancel_payment', name='cancel'),
    url(r'^start_payment/', 'glamazer.payments.views.start_payment', name='payment'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

glamazer/artists/forms.py
import string
import random
import os
import shutil
import base64
import re

from io import BytesIO
from PIL import Image

from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

from glamazer.core.helpers import get_object_or_None
from glamazer.artists.models import Artist
from glamazer.listings.models import Listing, Tags, ListingTags
from glamazer.settings import STYLE_INDEXES, MEDIA_URL, MEDIA_ROOT, DURATION



class ArtistForm(ModelForm):
    
    name = forms.CharField(required=True, widget=forms.TextInput())
    email = forms.EmailField(required=True, widget=forms.TextInput())
    password = forms.CharField(widget=(forms.PasswordInput()))
    confirm_password = forms.CharField(widget=(forms.PasswordInput()))

    class Meta:
        model = Artist
        fields = ['confirm_password', ]

    def clean_email(self):

        email = self.cleaned_data['email']
        check_email = User.objects.filter(email=email)

        if check_email:
            raise forms.ValidationError(
                "A user associated with this email address already exists")

        return email

    def clean_password(self):

        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if not password == confirm_password:
            raise forms.ValidationError("Password mismatch")

        elif len(password) < 6:
            raise forms.ValidationError("Password is too short (6 symbols)")

        elif password.isalpha() or password.isdigit():
            raise forms.ValidationError("Password should contain at least one alphabetic and one non-alphabetic character")

        return password

    def save(self):

        data = self.cleaned_data
        username = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(16))

        new_user = User.objects.create_user(
            username = username,
            first_name = data['name'],
            email = data['email'],
            password = data['password'],
            related_with = 'artists',
            )

        return new_user


class ArtistDetails(forms.Form):
    
    style = forms.ChoiceField(widget=forms.Select(), choices=STYLE_INDEXES)
    specific_style = forms.CharField()
    avatar = forms.ImageField(required=False, widget=forms.FileInput(attrs={'value': 'Click here to upload picture', 'class': 'custom_button' }))
    cropped_image = forms.CharField(required=False, widget=forms.HiddenInput())
    description = forms.CharField(widget=forms.Textarea())

    def __init__(self, *args, **kwargs):
        self.artist = kwargs.pop('artist', None)
        super(ArtistDetails, self).__init__(*args, **kwargs)

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']
        print(avatar)
        if not self.artist.avatar and not avatar:
            raise forms.ValidationError("This field is required.")

        return avatar

    def handle_uploaded_file(self, my_file, user):
        
        #format the data
        dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
        my_file = dataUrlPattern.match(my_file).group(2)
        artist_id = str(user.artist.id)
        path = '{0}artists/{1}/avatar/{1}.jpeg'.format(MEDIA_URL, artist_id) 
        full_path = '{0}artists/{1}/avatar/{1}.jpeg'.format(MEDIA_ROOT, artist_id)
        # check if the directory existings
        d = os.path.dirname(full_path)
        if not os.path.exists(d):
            os.makedirs(d)

        im = Image.open(BytesIO(base64.b64decode(my_file.encode('ascii'))))
        im.save(full_path, 'JPEG')

        return path


class LocationArtistDetails(forms.Form):
    
    address = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Enter street address'}))
    lat = forms.CharField(required=True, widget=forms.HiddenInput())
    lng = forms.CharField(required=False, widget=forms.HiddenInput())
    mobile_number = forms.CharField(required=True, widget=forms.TextInput())


class EditArtist(ModelForm):
    name = forms.CharField(required=True, widget=forms.TextInput())
    avatar = forms.ImageField(required=False, widget=forms.FileInput())
    description = forms.CharField(widget=forms.Textarea())
    address = forms.CharField(max_length=128, widget=forms.TextInput())
    style = forms.ChoiceField(widget=forms.Select(), choices=STYLE_INDEXES)
    lat = forms.CharField(required=False, widget=forms.HiddenInput())
    lng = forms.CharField(required=False, widget=forms.HiddenInput())
    mobile_number = forms.CharField(required=True)
    cropped_image = forms.CharField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = Artist
        exclude = ('money', 'rating', 'avatar', 'user', 'salon', 'step', 'currency')

    def save(self):

        artist = self.instance
        user = artist.user
        data = self.cleaned_data

        user.first_name = data['name']
        user.save()

        my_file = data['cropped_image']

        if my_file:

            dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
            my_file = dataUrlPattern.match(my_file).group(2)

            hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(10))
            path = MEDIA_URL + 'artists/' + str(user.artist.id) + '/avatar/' + hash_name + '.jpeg'
            full_path = MEDIA_ROOT + 'artists/' + str(user.artist.id) + '/avatar/' + hash_name + '.jpeg'

            artist.avatar = path
            artist.save()

            #if the folder doesn't exist, create one
            d = os.path.dirname(full_path)
            if not os.path.exists(d):
                os.makedirs(d)
            else:
                shutil.rmtree(d)
                os.makedirs(d)

            im = Image.open(BytesIO(base64.b64decode(my_file.encode('ascii'))))
            im.save(full_path, 'JPEG')

        else:
            artist.description = data['description']
            artist.address = data['address']
            artist.style = int(data['style'])
            artist.lat = data['lat']
            artist.lng = data['lng']
            artist.mobile_number = data['mobile_number']
            artist.save()
        return artist


class UploadListing(forms.Form):
    
    title = forms.CharField(required=True, widget=forms.TextInput())
    description = forms.CharField(required=True, widget=forms.Textarea(attrs={'placeholder': 'Enter description here.'}))
    price = forms.CharField(required=True, widget=forms.NumberInput())
    tags = forms.CharField(required=True, widget=forms.TextInput())
    duration = forms.ChoiceField(widget=forms.Select(), choices=DURATION)
    cover = forms.CharField(required=False, widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Listing

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UploadListing, self).__init__(*args, **kwargs)

    def clean_price(self):
        data = self.cleaned_data
        price = data['price']
        if not (len(price) in range(5) and price.isdigit()):
            raise forms.ValidationError('Please enter a valid price.')

        return price

    def clean_cover(self):
        data = self.cleaned_data
        cover = data['cover']
        pictures = self.request.POST.getlist('files')
        if not pictures:
            raise forms.ValidationError('Please upload a valid images.')

        return cover


    def save(self, artist, FILES):
        data = self.cleaned_data
        artist_id = str(artist.id)
        pictures = FILES.getlist('files')
        hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(6))

        for index, picture in enumerate(pictures):

            dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
            my_file = dataUrlPattern.match(picture).group(2)

            path = MEDIA_URL + 'artists/' + artist_id + '/listings/' + hash_name + '/'
            if index == int(data["cover"]):    
                full_path = MEDIA_ROOT + 'artists/' + artist_id + '/listings/' + hash_name + '/' + str(index) +'.jpeg'
                cover = full_path
            else:
                full_path = MEDIA_ROOT + 'artists/' + artist_id + '/listings/' + hash_name + '/' + str(index) +'.jpeg'

            #if the folder doesn't exist, create one
            d = os.path.dirname(full_path)
            if not os.path.exists(d):
                os.makedirs(d)

            im = Image.open(BytesIO(base64.b64decode(my_file.encode('ascii'))))
            im.save(full_path, 'JPEG')
        
        listing = Listing.objects.create(
            artist = artist,
            picture = path,
            title = data['title'],
            description = data['description'],
            picture_cover = cover,
            price = data['price'],
            metadata = hash_name,
            duration = int(data['duration']),
        )
        
        tags = data['tags'].split(',')
        tags.append(artist.get_style())
        for tag in tags:
            tag = tag.lower()
            current_tag = get_object_or_None(Tags, tag=tag)
            if not current_tag:
                current_tag = Tags.objects.create(tag=tag)

            ListingTags.objects.create(listing=listing, tags=current_tag)
        listing.save()
        return listing

templates/core/home.html
{% extends "master.html" %}
{% load thumbnail %}
{% load i18n %}

{% block meta %}
    <title>Partytask – booking platform for top event professionals and service providers</title>
{% endblock meta %}

    {% block stylesheet %}
        <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/jquery-ui.css">
    {% endblock stylesheet %}

    {% block content %}
<div id="content">
    <div class="home">
        <div class="column clear">
            <span class="text big">ORGANIZE YOUR PERFECT EVENT.</span>
            <span class="text"> FIND AND BOOK THE BEST SERVICE PROVIDERS AND PROFESSIONALS</span>
            <div class="container">
                <form method="GET" action="/result">
                    <div class="picker"><div class="icon calendar"></div><span>Date</span></div>
                    <div class="picker"><div class="icon time"></div><span>Time</span></div>
                    <div class="picker"><div class="icon service"></div><span>Service</span></div>
                    <div class="location"><div class="icon i_location"></div><input type="text"></div>
                    <input type="hidden" id="id_date" name="date" value="0">
                    <input type="hidden" id="id_time" name="hour" value="-1">
                    <input type="hidden" id="id_service" name="q" value="hair nails make up">
                    <input type="hidden" id="id_lat" name="lat">
                    <input type="hidden" id="id_lng" name="lng">
                    <input type="submit" class="custom_button" value="GO">
                </form>
            </div>
            <div class="trendy"><span class="arrow_down"></span><span class="arrow_down"></span>OR CHECK THE BEST EVENT OFFERS NEAR YOU<span class="arrow_down"></span><span class="arrow_down"></span></div>
        </div>
    </div>
    <div class="column">
        <ul class="gallery col_4">
            {% for listing in listings %}
                <li class="pic_view">
                    <ul>
                        <li class="picture">
                        <a href="/listings/{{ listing.id }}">
                            {% thumbnail listing.get_picture "240x143" crop="center" as im %}
                                <img src="{{ im.url }}">
                            {% empty %}
                                tc
                            {% endthumbnail %}
                            <div class="overlay"></div>
                        </a>
                        </li>
                        <li class="text">
                            <div class="title">{{ listing.title }}</div>
                            <p>
                                <div class="heart">{{ listing.likes }}</div>
                                <div class="price">$ {{ listing.price|floatformat:-3 }}</div>
                                <div class="comments">{{ listing.comments }}</div>
                            </p>
                        </li>
                        <li class="artist">
                        <a href="/artists/profile/{{ listing.artist_id }}">
                            {% thumbnail listing.artist.get_avatar "60x60" crop="center" as im %}
                                <img src="{{ im.url }}">
                            {% empty %}
                                tc
                            {% endthumbnail %}
                        </a>
                        </li>
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="select_date index date home" style="display: none;">
    <div class="container">
        <div id="date" style="position: relative; width: 100%; height: 100%">
            <div class="datepicker_container">
                <div id="datepicker_view"></div>
            </div>
        </div>
    </div>
</div>

<div class="select_date index time home" style="display: none;">
    <div class="container">
        <div id="date" style="position: relative; width: 100%; height: 100%">
            <div class="time_container">
                <div class="header">SELECT HOUR<a href="javascript:;">+</a></div>
                <ul class="col col_0">
                    <li>8:00AM</li>
                    <li>8:30AM</li>
                    <li>9:00AM</li>
                    <li>9:30AM</li>
                    <li>10:00AM</li>
                    <li>10:30AM</li>
                </ul>
                <ul class="col col_1">
                    <li>11:00AM</li>
                    <li>11:30AM</li>
                    <li>12:00PM</li>
                    <li>12:30PM</li>
                    <li>1:00PM</li>
                    <li>1:30PM</li>
                </ul>
                <ul class="col col_2">
                    <li>2:00PM</li>
                    <li>2:30PM</li>
                    <li>3:00PM</li>
                    <li>3:30PM</li>
                    <li>4:00PM</li>
                    <li>4:30PM</li>
                </ul>
                <ul class="col col_3">
                    <li>5:00PM</li>
                    <li>5:30PM</li>
                    <li>6:00PM</li>
                    <li>6:30PM</li>
                    <li>7:00PM</li>
                    <li>7:30PM</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="select_date index service" style="display: none;">
    <div class="container">
        <div id="date" style="position: relative; width: 100%; height: 100%">
            <div class="time_container">
                <div class="header">SELECT SERVICE<a href="javascript:;">+</a></div>
                <ul>
                    <li>Venues</li>
                    <li>Catering</li>
                    <li>Drinks</li>
                    <li>Other</li>
                </ul>
            </div>
        </div>
    </div>
</div>
    {% endblock content %}
    {% block scripts %}
    <script src="http://j.maxmind.com/app/geoip.js"></script>
    <script src="{{STATIC_URL}}js/ui.js"></script>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
    <script type="text/javascript">
        var geo_lat, geo_lng;

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(success, fail,{timeout:2000});
        } else {
            fail();
        }

        function success(position) {
            geo_lat = position.coords.latitude;
            geo_lng = position.coords.longitude;
            get_address(geo_lat,geo_lng);
        }

        function fail(){
            geo_lat = geoip_latitude();
            geo_lng = geoip_longitude();
            get_address(geo_lat,geo_lng);
        }

        function get_address(lat,lng){
            $.getJSON('http://maps.googleapis.com/maps/api/geocode/json?latlng=' + lat +
             ',' + lng + '&sensor=false',
            function(data){
                $('.location input').val(data.results['0']['formatted_address']);
                $('#id_lat').val(lat);
                $('#id_lng').val(lng);
            });
        }

        autocomplete = new google.maps.places.Autocomplete(
            ($('.location input')[0]),
            {
                types: ['geocode']
            });
            
            google.maps.event.addListener(autocomplete, 'place_changed', function() {
                lat = autocomplete.getPlace().geometry.location.lat();
                lng = autocomplete.getPlace().geometry.location.lng();
                $('#id_lat').val(lat);
                $('#id_lng').val(lng);
            });

        $('.picker').click(function(){
            if($(this).index() == 0)
            {
                $('.select_date.date').show();
            }
            else if ($(this).index() == 1)
                $('.select_date.time').show();
            else
                $('.select_date.service').show();
        });

        $(".col li").click(function(){
            $('.col').children().removeClass("active");
            $(this).addClass('active');
            $(this).closest(".select_date").hide();
            $('.picker:eq(1) span').text($(this).text());
            $("#id_time").val($(".col li").index(this))
        });

        $('.select_date').click(function(e){
            if($(e.target).hasClass('select_date'))
                $(this).hide();
        });

        $('.select_date.time .header a').click(function(e){
            $('.select_date.time').hide();
        });
        $('.select_date.service .header a').click(function(e){
            $('.select_date.service').hide();
        });

        $('.select_date.service li').click(function(e){
            $('.select_date.service li').removeClass('active');
            $(this).addClass('active');
            $(this).closest(".select_date").hide();
            $('.picker:eq(2) span').text($(this).text());
            $("#id_service").val($(this).text().toLowerCase())
        });

        function draw_picker(){
            $datapicker = $("#datepicker_view")
            $datapicker.datepicker(
                {
                    minDate: 0,
                    maxDate: "+1M +10D",
                    dayNamesMin: [ "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"],
                    dateFormat: "mm/dd/yy",
                    onSelect: function(dateText, inst){
                        $(".picker:eq(0) span").text($datapicker.val());
                        $(this).closest(".select_date").hide();
                        var temp = new Date(dateText)
                        $("#id_date").val(temp.getTime()/1000);
                    }
                });
            $datapicker.datepicker('show');
        }

        draw_picker()
        $('a.ui-state-default').click(function(){

            $(".select_date.date").hide()
        });
    </script>
    {% endblock scripts %}
    </body>
</html>