glamazer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'glamazer.core.views.home', name='home'),
    url(r'^venues/', 'glamazer.core.views.base', name='venues'),
    url(r'^catering/', 'glamazer.core.views.base', name='catering'),
    url(r'^drinks/', 'glamazer.core.views.base', name='drinks'),
    url(r'^music/', 'glamazer.core.views.base', name='music'),
    url(r'^entertainment/', 'glamazer.core.views.base', name='entertainment'),
    url(r'^equipment/', 'glamazer.core.views.base', name='equipment'),
    url(r'^decoration/', 'glamazer.core.views.base', name='decoration'),
    url(r'^party_goods/', 'glamazer.core.views.base', name='party'),
    url(r'^more/', 'glamazer.core.views.base', name='more'),
    url(r'^contest/', 'glamazer.core.views.base', name='contest'),
    url(r'^leaderboards/', 'glamazer.core.views.base', name='leaderboards'),
    url(r'^result/', 'glamazer.core.views.search', name='result'),
    url(r'^get_notifications/', 'glamazer.notifications.views.get_notifications', name='short_notifications'),
    url(r'^get_notifications_count/', 'glamazer.notifications.views.get_notification_count', name='notification_count'),
    url(r'^autocomplete_tags/', 'glamazer.core.views.autocomplete_tags', name='autocomplete_tags'),
    url(r'^sign_up/', TemplateView.as_view(template_name="sign_up.html"), name='signup'),
    url(r'^calendar/', TemplateView.as_view(template_name="core/calendar.html"), name='calender'),
    url(r'^success/', TemplateView.as_view(template_name="payments/success.html"), name='calender'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('glamazer.users.urls')),
    url(r'^artists/', include('glamazer.artists.urls')),
    url(r'^listings/', include('glamazer.listings.urls')),
    url(r'^favorites/', include('glamazer.favorites.urls')),
    url(r'^reviews/', include('glamazer.reviews.urls')),
    url(r'^success/', 'glamazer.payments.views.success_payment', name='success'),
    url(r'^error/', 'glamazer.payments.views.error_payment', name='error'),
    url(r'^cancel/', 'glamazer.payments.views.cancel_payment', name='cancel'),
    url(r'^start_payment/', 'glamazer.payments.views.start_payment', name='payment'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

glamazer/users/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^confirmation/(?P<email_token>.*)$', 'glamazer.users.views.confirmation', name='confirmation'),
    url(r'^change_password/(?P<email_token>.*)$', 'glamazer.users.views.change_password', name='change_password'),
    url(r'^forgotten_password/', 'glamazer.users.views.forgotten_password', name='forgotten_password'),
    url(r'^login/$', 'glamazer.users.views.login', name='login'),
    url(r'^sign_up/$', 'glamazer.users.views.sign_up', name='sign_up'),
    url(r'^logout/$', 'glamazer.users.views.logout_user', name='logout'),
    url(r'^whishlist/$', 'glamazer.users.views.whishlist', name='whishlist'),
    url(r'^followed/$', 'glamazer.users.views.followed', name='followed'),
    url(r'^change_email/$', 'glamazer.users.views.change_email', name='change_email'),
    url(r'^change_password_user/$', 'glamazer.users.views.change_password_user', name='change_password_user'),
    url(r'^sign_up/facebook', 'glamazer.users.views.facebook_registration', name='facebook_sign_up'),
    url(r'^login/facebook', 'glamazer.users.views.facebook_login', name='facebook_login'),
    url(r'^profile/$', 'glamazer.users.views.profile', name='user_profile'),    
    url(r'^profile/(?P<user_id>.*)', 'glamazer.users.views.profile', name='user_profile_user'),
    url(r'^settings', 'glamazer.users.views.settings', name='user_settings'),
    url(r'^bookings', 'glamazer.users.views.bookings', name='users_bookings'),
    url(r'^cancel', 'glamazer.users.views.cancel', name='booking_cancel'),
    url(r'^notifications/$', 'glamazer.notifications.views.show_notifications', name='user_notifications'),

)

glamazer/booking/models.py
import datetime

from django.db import models
from django.core.urlresolvers import reverse

from glamazer.notifications.models import Notification
from glamazer.listings.models import Listing
from glamazer.artists.models import Artist, CancellationPolicy, CancellationRate
from glamazer.users.models import Profile
from glamazer.core.helpers import current_time
from glamazer.core.emails import send_email
from glamazer.settings import STATUS, NOTIFICATIONS_LONG, NOTIFICATIONS_SHORT


class Booking(models.Model):
    artist = models.ForeignKey(Artist, null=True)
    client = models.ForeignKey(Profile)
    listing = models.ForeignKey(Listing)
    cancellation_policy = models.ForeignKey(CancellationPolicy)
    price = models.FloatField(default=0)
    revenue = models.FloatField(default=0)
    title = models.TextField(blank=True, null=True)
    start_time = models.IntegerField(default=0)
    end_time = models.IntegerField(default=0)
    description = models.TextField(blank=True, null=True)
    status = models.IntegerField(default=0)
    cancelled_by = models.IntegerField(default=0)
    is_mailed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return datetime.datetime.fromtimestamp(self.start_time).strftime('%Y-%m-%d %H:%M:%S')

    def get_status(self):
        return STATUS[self.status]

    def artist_link(self):
        url = '<a href="%s">%s</a>' % (reverse(("admin:artists_artist_change"), args=(self.artist_id, )), self.artist.user.first_name)
        return url

    def client_link(self):
        url = '<a href="%s">%s</a>' % (reverse(("admin:users_profile_change"), args=(self.client_id, )), self.client.user.first_name)
        return url

    def listing_link(self):
        url = '<a href="%s">%s</a>' % (reverse(("admin:listings_listing_change"), args=(self.listing_id, )), self.listing.title)
        return url


    artist_link.allow_tags = True
    artist_link.short_description = "Artist"
    
    client_link.short_description = 'Client'
    client_link.allow_tags = True

    listing_link.allow_tags = True
    listing_link.short_description = "Listing"

    def save(self, force_insert=False, force_update=False, old_status=None, **kwargs):
        if self.id:
            cancelled_by = self.cancelled_by
            super(Booking, self).save(force_insert, force_update)
            print("start_function", cancelled_by, old_status, self.status)
            if cancelled_by == 1 and not old_status == self.status:
                '''The real tricky moment here is the notation for nb 1 - the booking is approved, 2 - rejected, 3 declined'''
                notificated_user = self.client.user
                artist_user = self.artist.user
                if self.status == 1:
                    nb = 1
                    cr = CancellationRate.objects.get(artist=self.artist)
                    cr.approved += 1
                    cr.save()
                elif self.status == 2:
                    if old_status == 0:
                        nb = 2
                    else:
                        nb = 3
                        cr = CancellationRate.objects.get(artist=self.artist)
                        cr.cancelled += 1
                        cr.save()

                Notification.objects.create(
                    sender = artist_user,
                    receiver = notificated_user,
                    time = current_time(),
                    short_text = NOTIFICATIONS_SHORT[nb].format(artist=artist_user.first_name),
                    long_text = NOTIFICATIONS_LONG[nb].format(artist=artist_user.first_name, listing=self.listing.title, user_id=self.artist_id, metadata=self.listing_id),
                )

                kwargs = {}

                if nb == 1:
                    kwargs['listing'] = self.listing
                    kwargs['artistname'] = self.artist.user.first_name
                    kwargs['when'] = self.start_time
                    send_email(case=12, receiver=notificated_user, **kwargs)
                elif nb == 2:
                    kwargs['artistname'] = self.artist.user.first_name
                    send_email(case=13, receiver=notificated_user, **kwargs)
                elif nb == 3:
                    kwargs['artistname'] = self.artist.user.first_name
                    kwargs['when'] = self.start_time
                    kwargs['listing_id'] = self.listing_id
                    send_email(case=13, receiver=notificated_user, **kwargs)

            elif cancelled_by == 2 and not old_status == self.status:

                profile_user = self.client.user
                artist_user = self.artist.user
                Notification.objects.create(
                    sender = profile_user,
                    receiver = artist_user,
                    time = current_time(),
                    short_text = NOTIFICATIONS_SHORT[4].format(user=profile_user.first_name),
                    long_text = NOTIFICATIONS_LONG[4].format(user=profile_user.first_name, listing=self.listing.title, user_id=self.client_id, metadata=self.listing_id),
                )

                kwargs = {}
                # when user cancel an apoinment
                if old_status == 2:
                    delta_time = self.start_time - current_time()
                    kwargs['username'] = profile_user.first_name
                    kwargs['when'] = self.start_time 
                    kwargs['day_before'] = round(delta_time/86400)
                    if delta_time > 150000:
                        send_email(case=14, receiver=artist_user, **kwargs)
                    else:
                        send_email(case=15, receiver=artist_user, **kwargs)
        else:
            super(Booking, self).save(force_insert, force_update)
            user = self.client.user
            Notification.objects.create(
                        sender = user, 
                        receiver = self.artist.user,
                        time = current_time(),
                        short_text = NOTIFICATIONS_SHORT[0].format(user=user.first_name),
                        long_text = NOTIFICATIONS_LONG[0].format(user=user.first_name, listing=self.title, user_id=self.client_id, metadata=self.listing_id),
                    )
            kwargs = {}
            kwargs['listing'] = self.listing
            kwargs['username'] = user.first_name
            send_email(case=10, receiver=self.artist.user, **kwargs)


class DummyBooking(models.Model):
    artist = models.ForeignKey(Artist)
    client = models.ForeignKey(Profile)
    listing = models.ForeignKey(Listing)
    cancellation_policy = models.ForeignKey(CancellationPolicy)
    price = models.FloatField(default=0)
    title = models.TextField(blank=True, null=True)
    start_time = models.IntegerField(default=0)
    end_time = models.IntegerField(default=0)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

glamazer/users/forms.py
import string
import random
import os
import shutil
import base64
import re

from io import BytesIO
from PIL import Image

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.forms import ModelForm

from glamazer.users.models import Profile
from glamazer.core.helpers import get_object_or_None
from glamazer.settings import MEDIA_URL, MEDIA_ROOT


class ProfileForm(ModelForm):

    name = forms.CharField(required=True, widget=forms.TextInput())
    email = forms.EmailField(required=True, widget=forms.TextInput())
    password = forms.CharField(widget=(forms.PasswordInput()))
    confirm_password = forms.CharField(widget=(forms.PasswordInput()))

    class Meta:
        model = Profile
        fields = ['confirm_password', ]

    def clean_email(self):

        email = self.cleaned_data['email']

        check_email = get_object_or_None(User, email=email)

        if check_email and get_object_or_None(Profile, user=check_email, auto_created=True):
            raise forms.ValidationError(
                "A user associated with this email address already exists")

        return email

    def clean_password(self):

        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if not password == confirm_password:
            raise forms.ValidationError("Password mismatch")

        elif len(password) < 6:
            raise forms.ValidationError("Password is too short (6 symbols)")

        elif password.isalpha() or password.isdigit():
            raise forms.ValidationError("Password should contain at least one alphabetic and one non-alphabetic character")


        return password

    def save(self):

        data = self.cleaned_data

        check_email = get_object_or_None(User, email=data['email'])

        if not check_email:        
            username = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(16))

            new_user = User.objects.create_user(
                                username = username,
                                first_name = data['name'], 
                                email = data['email'], 
                                password = data['password'],
                                related_with="profiles",
                                )
            profile = Profile.objects.create(user=new_user)
        else:
            check_email.first_name = data['name']
            check_email.set_password(data['password'])
            check_email.save()
            
            profile = Profile.objects.get(user=check_email)
            profile.auto_created = False
            profile.save()

        return profile


class LoginUserForm(forms.Form):
    email = forms.EmailField(required=True, widget=forms.TextInput())
    password = forms.CharField(
        required=True, widget=forms.PasswordInput(render_value=False))
    remember_me = forms.BooleanField(required=False)

    def clean(self):

        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            user = authenticate(email=email, password=password)
            if user and user.is_active:
                return self.cleaned_data

        raise forms.ValidationError("Invalid login details")


class ChangePasswordForm(forms.Form):

    new_password = forms.CharField(required=True, widget=forms.PasswordInput(
        render_value=False))
    confirm_password = forms.CharField(required=True, widget=forms.PasswordInput(
        render_value=False))

    def clean(self):

        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if new_password != confirm_password:
            raise forms.ValidationError("Password mismatch")

        return self.cleaned_data


class ForgottenPasswordForm(forms.Form):
    email = forms.EmailField(required=True, widget=forms.TextInput())


class EditProfile(ModelForm):

    name = forms.CharField(required=True, widget=forms.TextInput())
    avatar = forms.ImageField(required=False, widget=forms.FileInput())
    cropped_image = forms.CharField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = Profile
        exclude = ('user',)

    def save(self):

        profile = self.instance
        user = profile.user
        data = self.cleaned_data

        user.first_name = data['name']
        user.save()

        my_file = data['cropped_image']

        if my_file:

            dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
            my_file = dataUrlPattern.match(my_file).group(2)

            hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(10))
            path = MEDIA_URL + 'users/' + str(profile.id) + '/avatar/' + hash_name + '.jpeg'
            full_path = MEDIA_ROOT + 'users/' + str(profile.id) + '/avatar/' + hash_name + '.jpeg'

            profile.avatar = path
            profile.save()

            #if the folder doesn't exist, create one
            d = os.path.dirname(full_path)
            if not os.path.exists(d):
                os.makedirs(d)
            else:
                shutil.rmtree(d)
                os.makedirs(d)

            im = Image.open(BytesIO(base64.b64decode(my_file)))
            im.save(full_path, 'JPEG')

        return profile

templates/user/bookings.html
{% extends "master.html" %}
{% load thumbnail %}
{% load i18n %}

{% block meta %}
    <title>Partytask – booking platform for top event professionals and service providers - Bookings</title>
{% endblock meta %}

    {% block content %}
    <script type="text/javascript" src="{{STATIC_URL}}js/moment.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/qtip.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.0.0.js"></script>

<div id="content">
    <div class="header">
        <span>BOOKINGS</span>
    </div>

    <div class="column">
        <table id="bookings">
            <thead>
                <tr>
                    <th>#</th>
                    <th>ORDER ID</th>
                    <th>DATE</th>
                    <th>LISTING</th>
                    <th>ORDERED BY</th>
                    <th>AMOUNT</th>
                    <th>STATUS</th>
                    <th>ACTION</th>
                </tr>
            </thead>
            <tbody>
                {% for b in bookings %}
                <tr data-number="{{ b.id }}" data-dialog="{{b.dialog}}" data-starttime="{{b.start_time}}" data-days="{{ b.days_before }}" data-percent="{{b.percent}}">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ b.id }}</td>
                    <td class="start_time_{{ b.id }}">

                    </td>
                    <td class="listing_view listing_view_{{b.id}}">
                        <a href="/listings/{{b.listing_id}}">{{b.title}}</a>
                    </td>
                    <td>
                        <a href="/artists/profile/{{b.artist_id}}">
                                {% thumbnail b.artist_avatar "55x55" crop="center" as im %}
                                    <img src="{{ im.url }}" style="border: 2px solid white; border-radius: 999px; width: 45px; height: 45px;">
                                {% empty %}
                                    <img src="{{ STATIC_URL }}img/default.png" style="width: 55px; height: 55px; border: 2px solid white; border-radius: 999px">
                                {% endthumbnail %}
                        </a>
                    </td>
                    <td>
                        {{b.currency}} {{b.price|floatformat:-3}}
                    </td>
                    <td>
                        {{b.status}}
                        <script type="text/javascript">
                            var b_id = {{b.id}} 
                            var start_time = {{ b.start_time }};
                            var start_time = moment(start_time*1000).format('h:mm a   MM/DD/YYYY');
                            $('.start_time_' + b_id).text(start_time);
                            $('.listing_view_' + b_id + ' a').qtip({
                              content: '{% thumbnail b.listing "200x112" crop="center" as im %}<img src="{{ im.url }}" style="width: 222px;" alt="listing">{% endthumbnail %}',
                              style: { width: { min: 222 } }
                            });
                        </script>
                    </td>
                    <td>
                        {% if not b.status == "REJECTED" %}
                            <form class="cancel" method="POST">
                                {% csrf_token %}
                                <input type="hidden" value="{{b.id}}" name="sn">
                                <input type="hidden" value="" name="cancellation_policy" class="cp">
                                <input type="submit" class="new_button red nb_hover" value="Cancel">
                            </form>
                        {% else %}
                                None
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                {% if bookings|length == 0 %}
                <tr class="pagination">
                    <td colspan='8'>
                        <div class="step-links">
                            Currently you don't have any bookings. 
                        </div>
                    </td>
                </tr>
                {% elif bookings.has_previous or bookings.has_next %}
                <tr class="pagination">
                    <td colspan='8'>
                        <div class="step-links">
                            {% if bookings.has_previous %}
                                <a href="?page={{ bookings.previous_page_number }}">&lt;</a>
                            {% endif %}

                            <span class="current">
                            {% for page in bookings.paginator.page_range %}
                                <a href="?page={{page}}" class='page{% if page == 0 or page == bookings.number %} active{% endif %}'>{{ page }}</a>
                            {% endfor %}
                            </span>

                            {% if bookings.has_next %}
                                <a href="?page={{ bookings.next_page_number }}">></a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
<div class="dialog_box" style="display: none">
    <div class="wrapper">
        <div class="head">WARNING!<a href="javascript:;">X</a></div>
        <div class="body">
            <div class="text"></div>
            <ul>
                <li class="Yes"><a class="new_button green nb_hover" href="javascript:;">Yes</a></li>
                <li class="No"><a class="new_button red nb_hover" href="javascript:;">No</a></li>
            </ul>
        </div>
    </div>
</div>
    {% endblock content %}

    {% block scripts %}
    <script type="text/javascript">
        $('form.cancel').submit(function(e){
            var $tr = $(this).closest('tr');
            var start_time = parseInt($tr.data('starttime'));
            var current_time = parseInt(new Date().getTime()/1000);
            var is_dialog = $tr.data('dialog');
            var days_before = parseInt($tr.data('days'))

            if (is_dialog)
            {
                var days_left = (start_time - current_time)/86400;
                if ( days_before > days_left )
                {
                    $('.dialog_box').data('number', $(this).closest('tr').data('number')).find(".text").html('They are less than ' + $tr.data("days") + ' days left to your reservation. In accordance to the artist <a href="">Cancelation policy</a>, if you cancel now, we will refund you with <b>' + $tr.data("percent") + '%</b> of the amount you paid.<br/><br/>Are you sure you want to cancel this appointment?').end().show();
                    e.preventDefault();
                }
            }
        });

        $('.dialog_box .head a, .dialog_box .body li.No a').click(function(){
            $('.dialog_box').hide();
        });

        $('.dialog_box .body li.Yes a').click(function(){
            $('tr[data-number="' + $('.dialog_box').data('number') + '"]').data("dialog", 0).find('form.cancel').find(".cp").val("1").end().submit();
        });
        
        $('.dialog_box').click(function(e){
            if($(e.target).hasClass('dialog_box'))
                $(this).hide()
        });
    </script>
    {% endblock scripts %}
</body>
</html>

templates/user/change_password.html
{% extends "master.html" %}
{% load i18n %}

{% block meta %}
    <title>Partytask – booking platform for top event professionals and service providers - Change Password</title>
{% endblock meta %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>CHANGE PASSWORD</span>
    </div>

    <div class="column">
        <div class="forms">
            <form class="login" method="post" action=".">
                {% csrf_token %}
                <input type="hidden" value="{{ email_token }}" name="token">
                <ul>
                    <li>
                        {% if form.new_password.errors %}
                            {{ form.new_password.errors }}
                        {% endif %}
                        <label for="" class="main_label">New Password</label></li>
                    <li>
                        {{ form.new_password }}
                    </li>
                    <li>
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password.errors }}
                        {% endif %}
                        <label for="" class="main_label">Confrim New Password</label></li>
                    <li>
                        {{ form.confirm_password }}
                    </li>
                    <li>

                        <input type="submit" value="Change Password">
                    </li>

                </ul>
            </form>
        </div>
    </div>
</div>

    {% endblock content %}

    {% block scripts %}
        <script src="{{STATIC_URL}}js/error.js"></script>
    {% endblock scripts %}
</body>
</html>

templates/user/followed.html
{% extends "master.html" %}
{% load i18n %}
{% load thumbnail %}

{% block meta %}
    <title>Partytask – booking platform for top event professionals and service providers - Followed</title>
{% endblock meta %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>FOLLOWED ARTISTS</span>
    </div>

    <div class="column">
            <ul class="gallery">
                {% for listing in listings %}
                <li class="pic_view">
                    <ul>
                        <li class="picture">
                            <a href="/listings/{{ listing.id }}">
                            {% thumbnail listing.get_picture "240x143" crop="center" as im %}
                                <img src="{{ im.url }}">
                            {% empty %}
                                tc
                            {% endthumbnail %}
                                <div class="overlay"></div>
                            </a>
                        </li>
                        <li class="text">
                            <div class="title">{{ listing.title }}</div>
                            <p>
                                <div class="heart">{{ listing.likes }}</div>
                                <div class="price">$ {{ listing.price|floatformat:-3 }}</div>
                                <div class="comments">{{ listing.comments }}</div>
                            </p>
                        </li>
                        <li class="artist">
                        <a href="/artists/profile/{{ listing.artist_id }}">
                            {% thumbnail listing.artist.get_avatar "60x60" crop="center" as im %}
                                <img src="{{ im.url }}">
                            {% empty %}
                                tc
                            {% endthumbnail %}
                        </a>
                        </li>
                    </ul>
                </li>
                {% endfor %}
            </ul>
            </div>
        </div>
    </div>
</div>

    {% endblock content %}

    {% block scripts %}

    {% endblock scripts %}
</body>
</html>

templates/user/login.html
{% extends "master.html" %}
{% load i18n %}

{% block meta %}
    <title>Partytask – booking platform for top event professionals and service providers - Login</title>
{% endblock meta %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>LOGIN</span>
    </div>

    <div class="column">
        <div class="forms">
            <form id="form_1" class="login" method="post" action=".">
                {% csrf_token %}
                    {% if user_form.errors %}
                        <ul class="errorlist"><li><ul class="errorlist"><li>Invalid login details</li></ul></li></ul>
                    {% endif %}
                <ul>
                    <li>
                        {% if user_form.email.errors %}
                            {{ user_form.email.errors }}
                        {% endif %}
                        <label for="" class="main_label">Email</label></li>
                    <li>
                        {{ user_form.email }}
                    </li>
                    <li>
                        {% if user_form.password.errors %}
                            {{ user_form.password.errors }}
                        {% endif %}
                        <label for="" class="main_label">Password</label></li>
                    <li>
                        {{ user_form.password }}
                    </li>
                    <li>
                        
                        <ul>
                            <li>{{ user_form.remember_me }} <label for="id_remember_me" class="main_label">Remember Me</label></li>
                            <li><a href="/users/forgotten_password">Forgotten password?</a></li>
                        </ul>

                        <input type="submit" name="log_user" value="Log In">
                    </li>
                    <li class="or">
                        <div></div>
                        <div class="or"> OR </div>
                    </li>
                    <li class="facebook">
                        <div class="facebook_icon"></div>
                        <input type="button" value="Log in with Facebook" onclick="log_me()">
                        <div class="fb-login-button" data-perms="email" data-scope="email" data-max-rows="1" data-show-faces="false"></div>
                        <div id="fb-root"></div>
                    </li>
                </ul>
            </form>
        </div>
    </div>
</div>

    {% endblock content %}

    {% block scripts %}
        <script src="http://connect.facebook.net/en_US/all.js"></script>
        <script src="{{STATIC_URL}}js/facebook.js"></script>
        <script src="{{STATIC_URL}}js/error.js"></script>
    {% endblock scripts %}
</body>
</html>